logging:
  level:
    '[org.springframework.cloud.gateway]': info
    '[org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator]': info
    '[org.springframework.cloud.gateway.route.RouteDefinitionMetrics]': info
    '[org.springframework.cloud.gateway.filter.GatewayMetricsFilter]': info

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://localhost:8761/eureka
    disable-delta: false
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 3

---
server.port: 10100

management.endpoints.web.exposure.include: routes, filters, refresh, health, beans, busrefresh, info, metrics, prometheus
management.server.port: 20100
management.tracing.sampling.probability: 1.0
otel.exporter.otlp.endpoint: http://rocky8-market:4318

spring:
  config.activate.on-profile: local, dev
  config.location: currentdir/config
  application.name: cloud-gateway
  
  data.redis.repositories.enabled: false
  
  reactor.context-propagation: AUTO
  
  cloud:
    loadbalancer:
      health-check:
        interval: 3s
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        # scheduler
        - id: scheduler
          predicates:
            - Path=/scheduler/**
          uri: lb://scheduler
          filters:
            - RewritePathFilter
            - TokenVerifyGatewayFilter
        
        # story
        - id: story-api
          predicates:
            - Path=/story-api/**
          uri: lb://story-api
          filters:
            - RewritePathFilter
            - TokenVerifyGatewayFilter
        
        # opendata
        - id: opendata-api
          predicates:
            - Path=/opendata-api/**
          uri: lb://opendata-api
          filters:
            - RewritePathFilter
            - TokenVerifyGatewayFilter

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    default-models-expand-depth: -1
    #try-it-out-enabled: false
    urls:
      - name: 1. Story API (story-api)
        url: /story-api/v3/api-docs
        
      - name: 2. Opendata API (opendata-api)
        url: /opendata-api/v3/api-docs
        
      - name: 3. Scheduler (scheduler)
        url: /scheduler/v3/api-docs

#cloud.gateway.filter.auth-url: http://localhost/auth-api/v1/token/verify-token

---
server.port: 10200

management.endpoints.web.exposure.include: routes, filters, refresh, health, beans, busrefresh, info, metrics, prometheus
management.server.port: 20200
management.tracing.sampling.probability: 1.0
otel.exporter.otlp.endpoint: http://rocky8-market:4318

spring:
  config.activate.on-profile: local-auth, dev-auth
  config.location: currentdir/config
  application.name: cloud-gateway-auth
  
  data.redis.repositories.enabled: false
  
  reactor.context-propagation: AUTO
  
  cloud:
    loadbalancer:
      health-check:
        interval: 3s
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        # auth
        - id: auth-api
          predicates:
            - Path=/auth-api/**
          uri: lb://auth-api
          filters:
            - RewritePathFilter

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    default-models-expand-depth: -1
    #try-it-out-enabled: false
    urls:
      - name: 1. Auth API (auth-api)
        url: /auth-api/v3/api-docs
