logging:
  level:
    '[org.springframework.cloud.gateway]': info
    '[org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator]': info
    '[org.springframework.cloud.gateway.route.RouteDefinitionMetrics]': info
    '[org.springframework.cloud.gateway.filter.GatewayMetricsFilter]': info

management:
  endpoints.web.exposure.include: routes, filters
  tracing.sampling.probability: 1.0
  tracing.propagation.consume: B3
  tracing.propagation.produce: B3_MULTI
  zipkin.tracing.endpoint: http://mgkim.net:59411/api/v2/spans

spring:
  profiles.active: local
  config.location: currentdir/config
  application.name: cloud-gateway

---
server.port: 10100

spring:
  config.activate.on-profile: local, dev
  
  data.redis.repositories.enabled: false
  
  reactor.context-propagation: AUTO
  
  cloud:
    loadbalancer:
      health-check:
        interval: 3s
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        # boot23
        - id: boot23-app
          predicates:
            - Path=/boot23-app/**
          uri: lb://boot23-app
          filters:
            - RewritePathFilter
          
        - id: boot23-soap
          predicates:
            - Path=/boot23-soap/**
          uri: lb://boot23-soap
          filters:
            - RewritePathFilter
        
        # boot27
        - id: boot27-app
          predicates:
            - Path=/boot27-app/**
          uri: lb://boot27-app
          filters:
            - RewritePathFilter
        
        # boot34
        - id: boot34-app
          predicates:
            - Path=/boot34-app/**
          uri: lb://boot34-app
          filters:
            - RewritePathFilter
        
        # story
        - id: story-api
          predicates:
            - Path=/story-api/**
          uri: lb://story-api
          filters:
            - RewritePathFilter
            - AuthFilter
        
        # opendata
        - id: opendata-api
          predicates:
            - Path=/opendata-api/**
          uri: lb://opendata-api
          filters:
            - RewritePathFilter
            - AuthFilter
        
        # market
        - id: market-api-customer
          predicates:
            - Path=/customer/**
          uri: lb://market-api-customer
          filters:
            - RewritePathFilter
          
        - id: market-api-delivery
          predicates:
            - Path=/delivery/**
          uri: lb://market-api-delivery
          filters:
            - RewritePathFilter
          
        - id: market-api-inventory
          predicates:
            - Path=/inventory/**
          uri: lb://market-api-inventory
          filters:
            - RewritePathFilter
          
        - id: market-api-order
          predicates:
            - Path=/order/**
          uri: lb://market-api-order
          filters:
            - RewritePathFilter
          
        - id: market-api-product
          predicates:
            - Path=/product/**
          uri: lb://market-api-product
          filters:
            - RewritePathFilter

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://localhost:8761/eureka
    disable-delta: false
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 3

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    default-models-expand-depth: -1
    #try-it-out-enabled: false
    urls:
      - name: Spring Boot 2.3.x APP (boot23-app)
        url: /boot23-app/v3/api-docs
        
      - name: Spring Boot 2.7.x APP (boot27-app)
        url: /boot27-app/v3/api-docs
        
      - name: Spring Boot 3.4.x APP (boot34-app)
        url: /boot34-app/v3/api-docs
        
      - name: Market Customer API (market-api-customer)
        url: /market-api-customer/v3/api-docs
        
      - name: Market Delivery API (market-api-delivery)
        url: /market-api-delivery/v3/api-docs
        
      - name: Market Inventory API (market-api-inventory)
        url: /market-api-inventory/v3/api-docs
        
      - name: Market Order API (market-api-order)
        url: /market-api-order/v3/api-docs
        
      - name: Market Product API (market-api-product)
        url: /market-api-product/v3/api-docs
        
      - name: Story API (story-api)
        url: /story-api/v3/api-docs
        
      - name: Opendata API (opendata-api)
        url: /opendata-api/v3/api-docs

#cloud.gateway.filter.auth-url: http://localhost/auth-api/v1/token/verify

---
server:
  port: 10200

spring:
  config.activate.on-profile: local-auth, dev-auth
  
  data.redis.repositories.enabled: false
  
  reactor.context-propagation: AUTO
  
  cloud:
    loadbalancer:
      health-check:
        interval: 3s
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        # auth
        - id: auth-api
          predicates:
            - Path=/auth-api/**
          uri: lb://auth-api
          filters:
            - RewritePathFilter

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://localhost:8763/eureka
    disable-delta: false
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 3

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    default-models-expand-depth: -1
    #try-it-out-enabled: false
    urls:
      - name: Auth API (auth-api)
        url: /auth-api/v3/api-docs
