server:
  port: 10100

spring:
  application.name: cloud-zuul
  profiles.active: local
  config.location: currentdir/config
  
zuul:
  set-content-length: false
  sensitive-headers: true
  
  routes:
    # boot23
    boot23-app:
      path: /boot23-app/**
      url: lb://boot23-app
    boot23-soap:
      path: /boot23-soap/**
      url: lb://boot23-soap
    
    # boot27
    boot27-app:
      path: /boot27-app/**
      url: lb://boot27-app
    
    # boot34
    boot34-app:
      path: /boot34-app/**
      url: lb://boot34-app
    
    # story
    story-api:
      path: /story-api/**
      url: lb://story-api
    
    # market
    market-api-auth:
      path: /market-api-auth/**
      url: lb://market-api-auth
    market-api-customer:
      path: /market-api-customer/**
      url: lb://market-api-customer
    market-api-delivery:
      path: /market-api-delivery/**
      url: lb://market-api-delivery
    market-api-inventory:
      path: /market-api-inventory/**
      url: lb://market-api-inventory
    market-api-order:
      path: /market-api-order/**
      url: lb://market-api-order
    market-api-product:
      path: /market-api-product/**
      url: lb://market-api-product

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://localhost:8761/eureka
    disable-delta: false
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 3

management:
  endpoints.web.exposure.include: routes, filters
