.variables_market-lib-common:
  variables:
    APP_NAME: "market-lib-common"

.build_market-lib-common:
  extends:
    - .variables_market-lib-common
  stage: build
  tags:
    - java17
  cache:
    key: "${CI_PROJECT_NAME}-gradle-cache"
    paths:
      - "$CI_PROJECT_DIR/.gradle/cache"
      - "$CI_PROJECT_DIR/.gradle/wrapper"
  script:
    - echo $PWD
    - java -version
    - ./gradlew :${APP_NAME}:build
